config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root to: "home#index"
  get "/about", to: "home#about"
  get "/contact", to: "home#contact"

  resources :xml, only: :index

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show

  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  resources :searchs, only: :index
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def create
    @comment = @post.comments.build comment_params
    @comment.user_id = current_user.id

    if @post.save
      render json: {status: :success, html: render_to_string(@comment)}
    else
      render json: {status: :error}
    end
  end

  def edit
    @comment = @post.comments.find_by id: params[:id]
    render json: {
      html: render_to_string(partial: "edit_comment", locals: {comment: @comment}),
      status: :success
    }
  end

  def update
    @comment = @post.comments.find_by id: params[:id]
    if @comment.update_attributes comment_params
      render json: {
        html: render_to_string(@comment),
        status: :success,
        id: @comment.id
      }
    else
      render json: {
        status: :error,
        message: :"Can not update comment"
      }
    end
  end

  def destroy
    @comment = @post.comments.find_by id: params[:id]
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to @post
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit :content
  end

  def find_post
    @post = Post.find_by id: params[:post_id]
  end
end

app/views/comments/_comment.html.erb
<div class="media response-info comment-row" id="<%= comment.id %>">
  <div class="media-left response-text-left">
    <%= image_tag "default-avatar.jpg", class: "img-responsive media-object" %>
    <h5 class="comment-user"><a href="#"><%= comment.user.name %></a></h5>
  </div>
  <div class="media-body response-text-right">
    <p><%= comment.content %></p>
    <ul>
      <li><%= comment.created_at.strftime Settings.posts.timestr %></li>
      <% if current_user == comment.user %>
        <%= link_to "Edit", edit_post_comment_path(comment.post, comment), class: "btn btn-info btn-sm edit-comment" %>
      <% end %>
      <% if current_user == comment.user || current_user.is_admin? %>
        <%= link_to "Delete", [comment.post, comment], remote:true, method: :delete, data: {comfirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="coment-form">
  <%= form_for [post, post.comments.build] do |f| %>
    <%= f.text_area :content, class: "form-control" %>
    <%= f.submit t(".comment"), class: "btn btn-info", id: "submit-comment" %>
  <% end %>
</div>

app/views/comments/_edit_comment.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center">Edit comment</h4>
      </div>
      <div class="modal-body">
         <%= form_for [comment.post, comment] do |f| %>
          <%= f.text_area :content, class: "form-control" %>
          <br>
          <%= f.submit "Update comment", class: "btn btn-info btn-block", id: "edit-comment" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/destroy.js.erb
toastr.success("Comment deleted <3");
$('#<%= @comment.id %>').fadeOut('slow');