config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root to: "home#index"
  get "/about", to: "home#about"
  get "/contact", to: "home#contact"

  resources :xml, only: :index

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show

  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
  end

  resources :searchs, only: :index
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-top">
    <div class="col-md-4 footer-grid">
      <h4><%= t ".blog" %> </h4>
      <ul class="bottom">
        <li><%= t ".author" %></li>
      </ul>
    </div>
    <div class="col-md-4 footer-grid">
      <h4><%= t ".message_us" %></h4>
      <ul class="bottom">
        <li><i class="glyphicon glyphicon-home"></i><%= t ".available" %></li>
        <li><i class="glyphicon glyphicon-envelope"></i>
          <%= link_to t(".mail"), "mailto:huymanhtmhp@gmail.com" %>
        </li>
      </ul>
    </div>
    <div class="col-md-4 footer-grid">
      <h4><%= t ".address_location" %></h4>
      <ul class="bottom">
        <li><i class="glyphicon glyphicon-map-marker"></i><%= t ".my_address" %></li>
        <li><i class="glyphicon glyphicon-earphone"></i><%= t ".phone" %></li>
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>
<div class="copy">
  <p>&copy; <%= t ".copy_right" %></p>
</div>
<div class="clearfix"> </div>

app/views/layouts/_header.html.erb
<div class="h-top" id="home">
  <div class="top-header">
    <ul class="cl-effect-16 top-nag">
      <li><%= link_to t(".home"), root_path, data: {hover: t(".home")} %></li>
      <% if user_signed_in? %>
        <li><%= link_to t(".log_out"), destroy_user_session_path,
          method: :delete, data: {hover: t(".log_out")} %></li>
        <li>
          <%= link_to t(".users"), users_path, data: {hover: t(".users")} %>
        </li>
        <li>
          <%= link_to t(".change_profile"), edit_user_registration_path, data: {hover: t(".change_profile")} %>
        </li>
        <li>
          <%= link_to t(".new_story"), new_post_path, data: {hover: t(".new_story")} %>
        </li>
        <li>
          <%= link_to t(".my_post"), posts_path, data: {hover: t(".my_post")} %>
        </li>
        <% if current_user.is_admin? %>
          <li>
            <%= link_to "Admin", admin_root_path %>
          </li>
        <% end %>
      <% else %>
        <li><%= link_to t(".registration"), new_user_registration_path,
          data: {hover: t(".registration")} %></li>
        <li><%= link_to t(".log_in"), new_user_session_path,
          data: {hover: t(".log_in")} %></li>
      <% end %>
      <li><%= link_to t(".about"), about_path,
        data: {hover: t(".about")} %></li>
      <li><%= link_to t(".contact"), contact_path,
        data: {hover: t(".contact")} %></li>
    </ul>
    <div class="search-box">
      <div class="b-search">
        <%= form_tag searchs_path, method: :get, id: "search-form" do %>
          <%= text_field_tag 'search', params[:search] %>
          <%= submit_tag "", id: "search-button" %>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/_nav-left.html.erb
<div class="logo">
  <%= link_to root_path do %>
    <h1><%= t ".blog" %></h1>
  <% end %>
</div>
<div class="top-menu">
  <span class="menu"> </span>
  <ul class="cl-effect-16">
    <li><%= link_to t(".home"), root_path, class: "#{yield :activeh}", "data-hover": t(".home") %></li>
    <li><%= link_to t(".about"), about_path, class: "#{yield :activea}",
      "data-hover": t(".about") %></li>
    <li><%= link_to t(".contact"), contact_path, class: "#{yield :activec}",
      "data-hover": t(".contact") %></li>
    <li><%= link_to t(".new_story"), "#", class: "#{yield :activen}",
      "data-hover": t(".new_story") %></li>
    <li><%= link_to t(".category"), "#", class: "#{yield :activeca}",
      "data-hover": t(".category") %></li>
    <li><%= link_to t(".gallery"), "#", class: "#{yield :activeg}",
      "data-hover": t(".gallery") %></li>
  </ul>

  <ul class="side-icons">
    <li><%= link_to "", "#", class: "fb" %></li>
    <li><%= link_to "", "#", class: "twitt" %></li>
    <li><%= link_to "", "#", class: "goog" %></li>
    <li><%= link_to "", "#", class: "drib" %></li>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Illuminati Blog</title>
    <%= csrf_meta_tags %>
    <link href="https://bootswatch.com/cosmo/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/custom.scss" rel="stylesheet">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Admin", admin_root_path, class: "navbar-brand" %>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Home", root_path %></li>
              <li>
                <%= link_to "Users", admin_users_path %>
              </li>
              <li>
                <%= link_to "Posts", admin_posts_path %>
              </li>
              <li><%= link_to "Logout", destroy_user_session_path %></li>
            <% else %>
              <li><%= link_to "Registration", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", "//fonts.googleapis.com/css?family=Open+Sans:700,700italic,800,300,300italic,400italic,400,600,600italic", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "shared/toastr_message" %>
    <%= render "layouts/header" %>

    <div class="full">
      <div class="col-md-10 col-md-offset-1 main">
        <%= yield %>
        <div class="clearfix"> </div>
      </div>
      <div class="clearfix"> </div>
    </div>
        <%= render "layouts/footer" %>

    <%= link_to "#home" do %>
      <span id="toTopHover" style="opacity: 1;"> </span>
    <% end %>
  </body>
</html>